# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: memory-postgres
    environment:
      POSTGRES_DB: memory
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: